CREATE TABLE DW.DimDate
(DateID                     INT NOT NULL,
 ActualDateLabel            VARCHAR(50) NULL,
 ActualDate                 DATE NULL,
 CalendarDayOfMonth         TINYINT NULL,
 CalendarDayOfYear          SMALLINT NULL,
 CalendarLastDayOfMonthFlag TINYINT NULL,
 CalendarMonth              TINYINT NULL,
 CalendarMonthAbbreviation  VARCHAR(12) NULL,
 CalendarMonthLabel         VARCHAR(50) NULL,
 CalendarQuarter            TINYINT NULL,
 CalendarQuarterLabel       VARCHAR(50) NULL,
 CalendarWeek               TINYINT NULL,
 CalendarWeekStartLabel     VARCHAR(50) NULL,
 CalendarWeekEndLabel       VARCHAR(50) NULL,
 CalendarYear               SMALLINT NULL,
 CalendarYearLabel          VARCHAR(50) NULL,
 DateDescription            VARCHAR(50) NULL,
 [DayOfWeek]                TINYINT NULL,
 DayOfWeekAbbreviation      VARCHAR(12) NULL,
 DayOfWeekLabel             VARCHAR(50) NULL,
 FiscalDayOfWeek            TINYINT NULL,
 FiscalDayOfMonth           TINYINT NULL,
 FiscalDayOfYear            SMALLINT NULL,
 FiscalMonth                TINYINT NULL,
 FiscalMonthAbbreviation    VARCHAR(12) NULL,
 FiscalMonthLabel           VARCHAR(50) NULL,
 FiscalQuarter              TINYINT NULL,
 FiscalQuarterLabel         VARCHAR(50) NULL,
 FiscalWeek                 TINYINT NULL,
 FiscalWeekStartLabel       VARCHAR(50) NULL,
 FiscalWeekEndLabel         VARCHAR(50) NULL,
 FiscalYear                 SMALLINT NULL,
 FiscalYearLabel            VARCHAR(50) NULL,
 HolidayFlag                TINYINT NULL,
 WeekendFlag                TINYINT NULL  ,
 --ETL Specific Columns
 ExecutionID                VARCHAR(50) NULL,
 InsertedDateTime           DATETIME DEFAULT(GETUTCDATE()) NULL,
 UpdatedDateTime            DATETIME DEFAULT(GETUTCDATE()) NULL,
 Hashvalue                  NVARCHAR(64) NULL,
 CONSTRAINT PK_DWDimDate__DateID PRIMARY KEY CLUSTERED(DateID ASC)
);
GO