CREATE TABLE Common.DimDate (
    DateID                          INT          NOT NULL,
    Actual_Date_Label               VARCHAR (50) NOT NULL,
    Actual_Date                     DATETIME     NOT NULL,
    Calendar_Day_Of_Month           TINYINT      NOT NULL,
    Calendar_Day_Of_Year            SMALLINT     NOT NULL,
    Calendar_Half_Year              TINYINT      NOT NULL,
    Calendar_Half_Year_Label        VARCHAR (50) NOT NULL,
    Calendar_Last_Day_Of_Month_Flag TINYINT      NOT NULL,
    Calendar_Month                  TINYINT      NOT NULL,
    Calendar_Month_Abbreviation     VARCHAR (12) NOT NULL,
    Calendar_Month_Label            VARCHAR (50) NOT NULL,
    Calendar_Trimester              TINYINT      CONSTRAINT DF_DimDate_Calendar_Trimester DEFAULT ((0)) NOT NULL,
    Calendar_Trimester_Label        VARCHAR (50) CONSTRAINT DF_DimDate_Calendar_Trimester_Label DEFAULT (' ') NOT NULL,
    Calendar_Quarter                TINYINT      NOT NULL,
    Calendar_Quarter_Label          VARCHAR (50) NOT NULL,
    Calendar_Week                   TINYINT      NOT NULL,
    Calendar_Week_End_Label         VARCHAR (50) NOT NULL,
    Calendar_Week_Label             VARCHAR (50) NOT NULL,
    Calendar_Week_Start_Label       VARCHAR (50) NOT NULL,
    Calendar_Year                   SMALLINT     NOT NULL,
    Calendar_Year_Label             VARCHAR (50) NOT NULL,
    Date_Description                VARCHAR (50) NOT NULL,
    Day_Of_Week                     TINYINT      NOT NULL,
    Day_Of_Week_Abbreviation        VARCHAR (12) NOT NULL,
    Day_Of_Week_Label               VARCHAR (50) NOT NULL,
    Days_In_Calendar_Month          TINYINT      NOT NULL,
    Days_In_Calendar_Year           SMALLINT     NOT NULL,
    Holiday_Flag                    TINYINT      NOT NULL,
    Weekday_Or_Weekend_Label        VARCHAR (12) NOT NULL,
    Weekend_Flag                    TINYINT      NOT NULL,
 
    CONSTRAINT PK_CommonDimDate__DateID PRIMARY KEY CLUSTERED (DateID ASC)
);

